### ISSUE TITLE
Mouse-over doesn't properly hide notifications when multiple notifications are cued

### ISSUE THREAD

**Issue by smathot** [dschreij/QNotifications#14]
Some notifications are supposed to hide on mouse-over so that they don't obstruct the GUI. This works for a single notification. However, when there are other notifications cued to be shown, the hidden notification is replaced, and the GUI is still obstructed. The ideal behavior would be that the currently visible notification is hidden, and that the next notification only appears when the mouse leaves the area.

Related to smathot/OpenSesame#712

**Comment by dschreij** [comment]
Hmm that will be difficult because if the notification is gone there is not really an area to work with, but I'll see what I can do.
