### ISSUE TITLE
Notification area should be hidden when there are no notifications

### ISSUE THREAD

**Issue by smathot** [dschreij/QNotifications#2]
Although the notification area is invisible when there are no notifications, it is not hidden, and can obstruct the controls below. For example, when I set the background color of the notification area to red, an empty notification area looks like this in OpenSesame:

![image](https://cloud.githubusercontent.com/assets/594936/14942458/e218d6c4-0fbd-11e6-8473-8f8226100791.png)

The easiest solution would be, I think, to `.hide()` the notification area when the last notification disappears, and `.show()` it when a new notification is added.

**Comment by dschreij** [comment]
Fixed! The notification area now is hidden if it has nothing to display, per your suggestion
