### ISSUE TITLE
Gracefully deal with large numbers of notifications

### ISSUE THREAD

**Issue by smathot** [dschreij/QNotifications#4]
Right now, there is no limit to the number of notifications that can be shown. In unusual cases, this can lead to the whole window being blocked by notifications.

See also:
- http://forum.cogsci.nl/index.php?p=/discussion/2225/

**Comment by dschreij** [comment]
Hmm judging from the forum discussion, it appears as if the safe-guard we built against showing the same notifications again within a certain time interval isn't working. I will have to look into that. I think we also noticed this ourselves last week? I can remember us having a short conversation about it.

Regarding the endless stacking of error messages, that has been a thorn in my side and high on my list to do something about. I just hoped it wouldn't become a real problem for anyone this soon. 

I propose implementing a queue structure: we place all messages in a queue. If a message closes, another one is fetched from the queue and shown. This process is repeated until the queue is empty. We can then also place a maximum on the number of messages that is shown at the same time: I think a maximum of two would be best. 
Maybe we should also place a maximum length on the queue. If more than 10 messages are queued at the same time, it probably means a lot of messages are repetitions or something else is wrong that so many notifications are being spit out.

**Comment by dschreij** [comment]
Alright, as of 1.1.0, QNotifications implements a message queue and only 2 notifications are shown simultaneously. The rest are placed in a queue, from which they are popped one-by-one each time a displayed notification disappears. This default max number of notifications can of course be changed by passing a different value to the constructor.
