### ISSUE TITLE
Add way to close all notifications at once

### ISSUE THREAD

**Issue by smathot** [dschreij/QNotifications#8]
Since the trouble with the OSF API (still not solved), I get a lot of notifications when I log into the OSF. This brought a usability problem to my attention: You have to click away each notification one by one! There should be a way to do this in one action. I'm not sure about the best implementation though.

- There could be a close-all button on each notification
- There could be an extra pseudonotification below the real notifications that says something like "Dismiss this to dismiss all notifications ×" This pseudonotification would then only be shown if there are more than the maximum number of notifications shown at once.
- Something else?

What do you think?

**Comment by dschreij** [comment]
Yes, I have noticed this as well. A "Dismiss further notifications" button should do the trick I think. I'll see if I can implement this in the near future. It should be a matter of emptying the list of notifications that are about to be shown.
Aside from this, it is quite weird and annoying that the OSF is still broken.

**Comment by smathot** [comment]
This has been effectively closed in #9.
